### ISSUE TITLE
Bug for postgres cleaner

### ISSUE THREAD

**Issue by Bayees** [emerleite/node-database-cleaner#28] opened 2015-06-25 12:22 UTC
Line 63 should be 
    db.query('DELETE FROM "' + table['table_name'] + '"', function(err) {

to get the right table name

**Comment by emerleite** [comment] 2015-07-15 01:29
I'll take a look.

**Comment by emerleite** [comment] 2015-07-15 02:05
@Bayees for me it's working fine. Could you give more information to try to reproduce?

**Comment by chamini2** [comment] 2016-05-27 15:34
This seems to be fixed by #23

**Comment by emerleite** [comment] 2016-07-25 18:55
Thanks @chamini2. Can you confirm It's ok @Bayees?

**Comment by emerleite** [comment] 2017-05-23 13:42
Fixed by #23

**Closed by emerleite** 2017-05-23 13:42 UTC
Labels: bug
